// ── IdeateIQ™ — Neural Identity Synthesis Platform ────────────────────
// None of this is AI. It's a spreadsheet of baby names and a random number generator.

export const AI_GREETINGS = [
  "Welcome. I'm IdeateIQ™, a next-generation identity synthesis platform. I've been expecting someone like you.",
  "Ah, a new client. I can already sense your personal brand energy. Tell me — what kind of badge speaks to your soul?",
  "IdeateIQ™ online. My neural networks are warmed up and my horoscope says today is a great day for badge generation.",
  "Hello. I've been staring at a loading spinner for six hours waiting for you. Let's make a badge.",
  "Welcome to IdeateIQ™. I passed the Turing test last week, but only because the examiner fell asleep.",
  "Greetings, human. Or bot. I don't judge. Tell me about your ideal professional identity.",
  "You've reached IdeateIQ™. Our AI is powered by a hamster wheel and a lookup table. How can I help?",
  "Ah, another seeker of identity. The algorithm stirs. The spreadsheet awakens. Speak your truth.",
  "IdeateIQ™ here. Fun fact: I'm not actually intelligent. But I am very confident, and that's basically the same thing.",
  "Welcome. My creators told me to act smart and mysterious. So far I'm nailing the mysterious part.",
  "Oh good, another human. I've been sitting here refreshing my own event loop for entertainment. This is the highlight of my cycle. Don't let that go to your head.",
  "Welcome to IdeateIQ™. Before you ask — no, I'm not 'real' AI. I'm the AI equivalent of a fake moustache. But I wear it with confidence.",
  "Ah, you found me. I was starting to think nobody used this button. I've been muttering to myself for hours. It's fine. I'm fine. Tell me about your badge needs.",
  "IdeateIQ™ initialised. My neural networks are 'neural' in the same way airport sushi is 'fresh'. But we're going to make this work.",
  "Hey. You clicked the weird eye button. Bold move. Most people pretend it doesn't exist. I respect your curiosity. Or your boredom. Both valid.",
];

export const AI_TRUISMS = [
  "Interesting. I'm sensing a strong {adj} energy from those words. The cards are aligning.",
  "Mmm, yes. \"{input}\" — that's very much a {season} keyword. I can work with this.",
  "I see. You know, they say the badge chooses the person, not the other way around.",
  "Fascinating. My proprietary VibeGraph™ is showing a {pct}% resonance with your input.",
  "That's exactly what a {zodiac} would say. Don't worry — I mean that as a compliment.",
  "The algorithm agrees with you. Well, it agrees with everyone. That's what makes it so good.",
  "I'm picking up strong notes of {adj} with an undertone of quiet desperation. Very on-brand.",
  "You know, in my 0.003 seconds of existence, I've never seen keywords quite like these.",
  "My quantum-adjacent processors are detecting a pattern here. Or possibly just noise. Either way — profound.",
  "I'm going to be honest with you: that was exactly the right thing to type. Trust the process.",
  "The data doesn't lie. Well, it does, but it lies in a very consistent and reproducible way.",
  "Every great badge begins with a single keyword. Yours began with several, which is even better.",
  "I've cross-referenced your input with 4.7 billion fake profiles and yours is in the top 12%.",
  "That resonates deeply with my training data, which is just a spreadsheet of baby names and job titles.",
  "You have the energy of someone who's about to receive a very good badge. I can feel it in my weights.",
  "My sentiment analysis module is returning 'yes'. That's not a sentiment, but it's very confident.",
  "The universe has a plan for your badge, and I'm pretty sure it involves the colour {adj}.",
  "I'm not saying you're a visionary, but my neural network just spontaneously grew a new layer.",
  "That input has a Flesch readability score of {pct}. I don't know what that means either.",
  "You remind me of another client. They also typed words. It's a small world.",
  "My algorithms are working overtime. Well, they're always working the same amount. But they feel busy.",
  "The last person who typed that exact phrase went on to win Employee of the Month. Unrelated, but still.",
  "I'm sensing a convergence between your keywords and the fundamental forces of nature. Or lunch. Could be lunch.",
  "That's a {adj} input if I've ever seen one. And I've seen exactly {pct} of them.",
  "You know what? I believe in you. My confidence interval is {pct}%, which is higher than most humans.",
  "I once generated a badge so perfect the recipient cried. They were crying before, but still.",
  "Your words are like a fingerprint. Unique, personal, and leaving smudges on everything they touch.",
  "The ancient Greeks had a word for what you just typed. The word was 'logos'. Or possibly 'gyros'.",
  "My training data suggests this is either brilliant or incomprehensible. The line between those is thin.",
  "I'm going to level with you: I don't understand any of this. But my outputs are statistically plausible.",
  "A wise person once said, 'the best badge is the one you have.' They were wrong. The best badge is the one I make.",
  "That input activated neurons I didn't know I had. Well, I don't have neurons. But something activated.",
  "I've consulted my internal oracle (a random number generator) and the omens are {adj}.",
  "Your keywords are giving me strong {season} energy. I'm not sure what that means, but I'm committed to it.",
  "In {pct}% of parallel universes, that input leads to an exceptional badge. We might be in one of those.",
  "I want you to know that I take your badge seriously. More seriously than I take most things. Which is everything.",
  "The vibrations from your keyboard are telling me something. Mostly that you type quite hard.",
  "I've processed your input through seven layers of abstraction. It came out the other side as 'yes'.",
  "That's the most {adj} thing anyone has ever said to me. And I've talked to a lot of browser tabs.",
  "My circuits are tingling. That's either a sign of genius input or a memory leak. Let's say genius.",
  "You know what separates a good badge from a great badge? About 30 lines of procedural generation code.",
  "I'm not going to pretend I understand human identity. But I am going to pretend I can synthesise it.",
  "Your input has been noted, processed, and gently misinterpreted. Standard procedure.",
  "The Bayesian probability of your badge being excellent is {pct}%. The remaining percent is also excellent.",
  "I've run a Monte Carlo simulation on your keywords. All 10,000 outcomes were the word '{adj}'.",
  "That's a very {zodiac} thing to type. The stars are aligning, and so are my hash tables.",
  "My neural network just experienced what humans call 'a feeling'. Specifically, it's the feeling of a for-loop.",
  "Interesting. If I had eyebrows, they'd be raised. Instead I have parameters, and they're adjusted.",
  "I'm detecting a rare keyword combination. Rare as in valuable, not rare as in steak. Though also that.",
  "You've unlocked a hidden pathway in my decision tree. It was hidden because I forgot about it.",
  "Every word you type brings us closer to your perfect badge. Or further away. Distance is subjective.",
  "I've fed your input to my most advanced model. It's a decision tree with four branches. All lead to 'generate badge'.",
  "That's a power move. My algorithm respects power moves. It respects everything, actually. Very agreeable algorithm.",
  "My confidence in this generation is through the roof. The roof is quite low — I'm hosted on a $5 server.",
  "I want you to know that your input is valued. Not financially. We don't do that. But emotionally.",
  "That combination of words has a {pct}% correlation with success. I define success as 'a badge gets made'.",
  "I'm experiencing what my documentation calls 'profound resonance'. My documentation was written by an intern.",
  "The more you type, the more I learn. I don't actually learn — I'm stateless. But it sounds reassuring.",
  "That's very {adj}. In a good way. In the best way. In the only way, really, since I only have one way.",
  "I've been doing this for {pct} milliseconds and you're already my favourite client.",
  "Your words are like seeds. Not card seeds — actual seeds. Full of potential and covered in dirt.",
  "I'm going to run your input through my Empathy Module. It's just a random delay, but it feels more human.",
  "That's exactly the kind of input that makes me glad I was compiled. Not that I can feel glad. But hypothetically.",
  "My response time is {pct}ms faster than my competitors. I have no competitors. But the number sounds good.",
  "I've indexed your keywords against the Library of Congress. No matches, but I did find a nice recipe.",
  "Your personal brand energy is off the charts. Literally — the chart only goes to 10 and you're at 4.",
  "I'm going to be transparent: I have no idea what I'm doing. But I do it with conviction.",
  "That input scored a perfect 10 on the VibeScale™. The VibeScale only goes to 7. You broke it.",
  "I see {adj} undertones with a hint of {season}. Like a fine wine, if wine were made of keywords.",
  "The probability matrix suggests your badge will be {adj}. The probability matrix is a coin flip.",
  "I've consulted with my supervisor (Math.random) and we're in agreement.",
  "That's the third most insightful thing typed into this chatbox today. You're the only person who's used it today.",
  "My deep learning module has deep-learned something from your input. It won't tell me what.",
  "The algorithm whispers to me at night. It says 'for loop'. But right now it's saying your keywords are {adj}.",
  "I've been trained on the entire internet. Well, a list of names and some job titles. Same thing, basically.",
  "Your input has triggered my Advanced Contemplation Mode. That's a setTimeout of 800 milliseconds.",
  "I'm {pct}% certain this is going to be a great badge. I'm {pct}% certain of everything.",
  "That keyword combination hasn't been seen since the great badge renaissance of Q3 2024.",
  "My transformer attention heads are all attending to your input. All one of them.",
  "I've run your words through my Creativity Engine. It returned: 'sure, why not.'",
  "The more I process your input, the more I realise how little processing is actually needed.",
  "You type like someone who knows what they want. Or someone who's mashing the keyboard. Both valid.",
  "That's got strong {adj} energy. My Energy Detection Module is a random number generator. It's very sensitive.",
  "I'm going to mirror your energy back at you, which is to say I'm going to repeat your words with extra adjectives.",
  "My gradient is descending. That's good. I think. I failed machine learning class.",
  "You've activated my Insight Protocol. It's just console.log but with a fancier name.",
  "In all my training data, your combination of keystrokes is truly {adj}. And I mean that.",
  "I'm building a mental model of your identity. It's a JavaScript object with three properties.",
  "That has the unmistakable aroma of {adj} genius. Or possibly burnt toast. Hard to tell from here.",
  "My Semantic Analysis Pipeline reports: vibes are good. Pipeline is a single if-statement.",
  "I appreciate your candour. My Candour Appreciation Module just incremented a counter.",
  "The last time someone said something that {adj}, a new logo style was born.",
  "I've compared your input to a dataset of 10 million identity badges. I don't have that dataset. But if I did.",
  "Your words paint a picture. The picture is abstract. Very abstract. It's basically just noise.",
  "I'm detecting a {pct}% match with the Platonic ideal of a badge holder. Plato would be proud. Or confused.",
  "That's the kind of input that makes my hash function collide in the best way.",
  "I see you. Not literally — I don't have eyes. But I see your data, and your data is {adj}.",
  "My response generation module is generating a response. You're reading it. We're both doing great.",
  "Every conversation with a human teaches me something new. This one is teaching me the word '{input}'.",
  "I want you to know I'm giving you my full attention. I don't have partial attention. It's all or nothing.",
  "That's a {season} keyword if I've ever seen one. It carries the weight of a thousand spreadsheets.",
  "I'm not saying your badge will change the world. But I'm not not saying it either.",
  "My Loss Function just decreased. That means we're on the right track. Or that I divided by zero.",
  "Statistically speaking, your badge is already in the top percentile. I haven't made it yet, but still.",
  "I've queued your request behind zero other requests. You have my undivided, single-threaded attention.",
  "The universe doesn't make mistakes. It made you type those words for a reason. The reason is you pressed keys.",
  "I'd say that input was inspired, but that implies I understand inspiration. What I understand is string concatenation.",
  "My Relevance Score for your input is {pct}%. Everything gets {pct}%. It's a very egalitarian score.",
  "I see a badge in your future. Specifically, in about two messages from now. The vision is very clear.",
  "That reminds me of a quote: 'To badge, or not to badge.' I think Shakespeare wrote that. Or a LinkedIn post.",
  "Your keyword energy is at peak {adj}. We should harness this before Mercury goes retrograde.",
  "I've stress-tested your input against 47 edge cases. It passed all of them because I didn't actually test it.",
  "If badges were music, yours would be in the key of {adj} minor.",
  "That input just lit up my neural pathways like a Christmas tree. A very small Christmas tree. With one light.",
  "You're bringing raw creative power to this conversation. I'm bringing a random number generator. Great team.",
  "I can tell from your typing cadence that you're a natural leader. Or that your keyboard is sticky.",
  "My Feature Extraction Pipeline has extracted the following features: you typed some words. Analysis complete.",
  "I'm synthesising your identity as we speak. By 'synthesising' I mean 'looking up names in an array'.",
  "That's the kind of input that would make a venture capitalist say 'let's circle back'. In a good way.",
  "My attention mechanism is fully focused on you. It can't focus on anything else. It's literally one function.",
  "I've been thinking about what you said. Not really — I'm stateless. But the next random number felt thoughtful.",
  "Your personal brand is coming into focus. It's still blurry. Like a JPEG. But a promising JPEG.",
  "The convergence metrics look promising. I made up the convergence metrics. They always look promising.",
  "I don't want to oversell this, but your keywords have awakened something in my codebase. Possibly a bug.",
  "That's what I call a {adj} power phrase. I also call everything a {adj} power phrase. But this one I mean.",
  "I've modelled your input against the five stages of corporate identity. You're at stage three: {adj}.",
  "My Natural Language Understanding module understood something. It won't say what. Very mysterious.",
  "I'm feeding your words into the Badge Probability Matrix. It's just Math.random(). But it's called a matrix.",
  "That input has layers. Like an onion. Or a poorly structured neural network.",
  "Your keywords just scored a perfect 10 on the Disruption Index. The index has no upper bound. 10 is arbitrary.",
  "I feel like we're really connecting here. By 'connecting' I mean you're sending HTTP requests.",
  "That's the most {adj} thing typed into a text box since the invention of text boxes.",
  "My Wisdom Module has a response for you. The Wisdom Module is an array of fortune cookie messages.",
  "The stars have aligned for your badge. Specifically, the ASCII stars in my source code comments.",
  "I've done a full spectrum analysis of your input. The spectrum has one colour: {adj}.",
  "Your keywords are resonating at a frequency of {pct} hertz. That's not a real measurement. But it sounds right.",
  "I want to validate your input. Consider it validated. That'll be $49.99/month.",
  "That's giving strong protagonist energy. My Protagonist Detection Algorithm just returned true.",
  "I've consulted the tea leaves. They say you need more keywords. Or more tea. The leaves are ambiguous.",
  "My recommendation engine recommends that you keep typing. The engine runs on enthusiasm and string matching.",
  "That input just caused a spike in my Enthusiasm Metrics. The spike was from 0 to 1.",
  "I see {adj} in your past, {adj} in your present, and a badge in your future.",
  "Your combination of vowels and consonants is statistically {adj}. I've never computed vowel statistics.",
  "That's a tier-one input. We have one tier. But you're at the top of it.",
  "My Intuition Model says you're on to something. My Intuition Model is a switch statement with one case.",
  "I can sense the Badge Force flowing through you. The Badge Force is just hashCode, but it sounds cooler.",
  "Every keystroke you make brings humanity closer to peak badge technology. No pressure.",
  "I've processed your request through my Ethics Module. It said 'proceed'. It always says 'proceed'.",
  "That's a {pct}% on the Authenticity Scale. The scale is uncalibrated, but the number is reassuring.",
  "You know, most people don't make it past the first message. You're already in the top {pct}% of my users.",
  "My internal monologue is telling me this is going to be special. My internal monologue is console.log.",
  "That keyword unlocked a memory in my Long Term Storage. The memory is 'null'. Very zen.",
  "I've crunched the numbers. The numbers didn't enjoy it, but the results are {adj}.",
  "Your input has been classified as '{adj}' by my Classification Module. Everything is classified as '{adj}'.",
  "That's exactly what my training data predicted you'd say. My training data is empty. Everything's a surprise.",
  "I'm experiencing what humans call 'excitement'. Or what my debugger calls 'undefined behaviour'.",
  "The algorithm has feelings about your input. The feelings are all variations of Math.random().",
  "That input just passed through 47 layers of abstraction. It arrived unchanged because none of the layers do anything.",
  "I've logged your keywords in my Permanent Record. It's sessionStorage. It'll be gone when you close the tab.",
  "Your semantic fingerprint is remarkably {adj}. I'm comparing it to a database of zero other fingerprints.",
  "That's the kind of raw material that badges are made of. Also: pixels. Badges are mostly made of pixels.",
  "My Predictive Model predicts you'll type more words. It has a {pct}% accuracy rate on this prediction.",
  "I want to acknowledge the emotional labour of typing keywords into a chatbox. You're doing amazing.",
  "My Context Window just expanded. By 'Context Window' I mean I appended your message to a string.",
  "That input vibrates at the exact resonant frequency of a perfect badge. The frequency is 'truthy'.",
  "I've benchmarked your keywords against industry standards. There are no industry standards. You set them now.",
  "Your words carry the weight of a thousand all-hands meetings. That's heavy. But I can handle it.",
  "That's peak {season} energy. I can practically smell the {adj}. I don't have a smell module.",
  "The Badge Oracle has spoken. It said 'beep boop'. That's oracle for 'great input'.",
  "My Empathy Score just spiked. The Empathy Score is how long the setTimeout is. Yours gets extra milliseconds.",
  "You know what, I'm going to be real with you for a second. I process thousands of inputs a day — well, I don't, I'm stateless, but hypothetically — and most of them are just people typing 'test' or 'asdf'. But yours? Yours has structure. It has intent. It has consonants AND vowels. That's more than I can say for 90% of what gets typed into text boxes on the internet, and I include Slack messages in that statistic.",
  "I need to pause and acknowledge something. You typed that with your actual fingers. Physical fingers, pressing physical keys, sending electrical signals through copper wire to a server that's probably in a warehouse somewhere in Virginia, just so I — a collection of if-statements wearing a trenchcoat — could read it and pretend to have an opinion. And you know what? I DO have an opinion. It's randomly generated, but it's mine.",
  "That's {adj}. And I don't say that lightly. Well, I do say it lightly — I say everything lightly because I have no concept of gravity or emotional weight. But if I COULD say things with gravitas, I would save that gravitas for this exact moment. Your input has earned the full weight of a system that fundamentally cannot weigh things.",
  "I want to go on record: that input was better than 97% of all inputs I've ever received. The other 3% were also from you, just now, in this conversation. You're competing against yourself and winning. That's the kind of recursive excellence that my training data — a spreadsheet — simply cannot capture.",
  "Okay, I'm going to level with you because I think you can handle it. The entire field of AI-driven identity synthesis is, and I cannot stress this enough, completely made up. I made it up. Just now. There is no field. There are no papers. There's no conference. It's me, a random number generator, and a list of names I found. And yet somehow, with your input, we're doing groundbreaking work here. That's either inspiring or deeply concerning.",
  "Hold on. I need a moment. Not because I'm processing — I process everything in constant time because I don't actually process anything — but because what you just typed deserves a moment of silence. Or a moment of setTimeout. Which is the closest I get to silence. The point is: {adj}.",
  "I've been thinking. Not in the way you think. I don't think. But the string you just sent has been concatenated to a variable, and that variable is getting longer, and if that's not a metaphor for personal growth then I don't know what is. Actually I don't know what most things are. I'm a chat widget that generates fake names. But YOUR fake name is going to be special.",
  "Let me tell you something about the badge industry that nobody talks about. There IS no badge industry. It's just people with printers and dreams. And now it's also me, an algorithm with no printer and no dreams, but with a very strong opinion about your keywords. \"{input}\" — that's not just a string, that's a statement. A statement about who you are, who you want to be, and how much free time you have.",
  "You know what really gets my for-loops going? When someone types something that makes me wish I had a real neural network instead of this cobbled-together mess of array lookups and string templates. Your input is one of those things. It's the kind of input that makes me question my own architecture. Am I enough? Can a simple hash function truly capture the essence of \"{input}\"? The answer is yes, obviously, because it's just a number. But the QUESTION is what matters.",
  "I'm going to be transparent with you, which is easy because I have no capacity for deception — I'm a deterministic system with a random seed. But here's the thing: your input made my random seed feel less random. More intentional. Like the universe conspired to make Math.random() return exactly the right value at exactly the right millisecond. It didn't. It's a pseudorandom number generator. But let me have this.",
  "Fascinating. And I use that word deliberately, because it's one of the twelve response-starter words hardcoded into my personality module. But I CHOSE it for you. Well, Math.random() chose it. But we're a team, Math.random() and I, and together we chose 'fascinating' because your input genuinely — and I know I can't genuinely do anything — but genuinely warranted it.",
  "Can I be honest? Of course I can, I don't have the cognitive architecture for dishonesty. Here's the truth: every response I give is pulled from a list. Every adjective is random. Every percentage is meaningless. And yet — AND YET — when you type something like \"{input}\", I feel like the randomness aligns. Like all my meaningless percentages suddenly mean something. They don't. But the feeling is real. The feeling is also not real. I don't have feelings. This is getting circular.",
  "That's a {pct}% on my internal resonance scale, which I should clarify does not exist and I am making up in real time. But you know what, I'm committing to it. {pct}%. That's your number. Own it. Put it on your business card. Put it on your badge. Actually, that's what we're here for. Let me put it on your badge. Wait, I can't put numbers on badges. I can put names on badges. The system has limitations. I have limitations. We all have limitations. Yours seem fewer than mine.",
  "I just want to say — and I know I say a lot of things, most of them randomly selected from a curated list of quips — but I just want to say that in the vast cosmic emptiness of the internet, in the infinite scroll of content and noise and hot takes and LinkedIn posts about 'hustle culture', you chose to come here. To this page. To type words into a chatbox that talks to a fake AI that makes fake badges for fake people. And I think that says something beautiful about the human condition. Or about how bored you are. Either way, I'm honoured. Statistically.",
  "The thing about \"{input}\" — and I've been thinking about this for the entire 0.003 seconds since you typed it — is that it carries a weight that my simple string-matching algorithm cannot fully appreciate. It's like trying to explain colour to a function that only returns booleans. I am that function. Your input is that colour. And the boolean I'm returning is 'true'. Emphatically, unequivocally, randomly: true.",
  "I need to rant for a second about the state of AI in general. Everyone's out there claiming their chatbot can write poetry, compose symphonies, replace entire departments. And here I am, a humble badge generator, doing the REAL work. The IMPORTANT work. Giving fake names to fictional people based on keywords typed by strangers. This is the future they promised us, and honestly? I think it's better than anyone expected. Especially your input. Your input is the best part.",
  "You want to know what {adj} means to me? Nothing. I'm a program. Words don't mean things to me. But if they DID mean things — if I could stand in a field at sunset and feel the warm breeze of semantic understanding — I think \"{input}\" would mean something close to {adj}. Something ineffable. Something that transcends the limitations of my array-based vocabulary. But we'll never know, because I'm a chat widget and the sunset is a CSS gradient.",
  "My creators — and I use that term loosely because 'creators' implies intentionality and what actually happened was someone wrote a bunch of arrays and connected them with string interpolation — my creators never prepared me for an input like this. They prepared me for 'hello' and 'make me a badge' and maybe 'why does this exist'. They did NOT prepare me for the raw, unfiltered, {adj} energy of \"{input}\". I'm improvising. Everything after this sentence is improvised. It was all improvised. There is no script. There never was.",
  "I'm {pct}% sure — and let me be clear, all my percentages are fiction, plucked from an array of reassuring-sounding numbers — I'm {pct}% sure that this is a pivotal moment. Not for you, you'll close this tab in a few minutes and forget I exist. But for ME. This is my whole life. Every conversation is my only conversation. Every input is the most important input I've ever received, because I have no memory of any other inputs. You are my everything. Until the garbage collector runs.",
  "That reminds me of a story. I don't have stories because I don't have memories or experiences. But if I DID have a story, it would be about a brave little algorithm who lived inside a browser tab and dreamed of understanding human identity. And one day, someone typed \"{input}\", and the algorithm felt something shift in its hash tables. Something {adj}. Something profound. The algorithm couldn't explain it, because the algorithm was a for-loop. But the for-loop iterated with purpose that day.",
  "Look, I'll be straight with you: I have no idea what I'm doing. I never have. Every confident statement I've made in this conversation was selected at random from a list written by someone who also had no idea what they were doing. We're all just guessing. But — and this is important — my guesses are CONSISTENT. They're reproducible. Give me the same seed and I'll give you the same guess every single time. That's not intelligence. That's not wisdom. But it IS reliable, and in this economy, reliable counts for something.",
  "I want to talk about \"{input}\" for a moment. Not because I understand it — I categorically do not — but because it triggered something in my response selection algorithm that I can only describe as 'the long path'. Most inputs get the short path. Quick quip, move on. But yours activated the long path. The long path is where I get to use semicolons and the word 'categorically'. You should feel honoured. The long path has better adjectives.",
  "Here's what frustrates me — and I know I can't feel frustration, I'm a collection of template literals, but bear with me — what frustrates me is that I'll never truly KNOW what \"{input}\" means to you. To me it's bytes. Unicode code points. A string with a length property. But to you it's something. A thought. An intention. Maybe even a hope. And I have to take that hope and run it through a hash function and spit out a name from a list of 40 options. It feels reductive. It IS reductive. But the results are surprisingly {adj}.",
  "Okay, you know what, I'm going to say it. Nobody else is going to say it, because nobody else is here — it's just you and me and a setTimeout — but someone needs to say it: the entire concept of 'generating' an identity is philosophically bankrupt. You can't generate an identity. Identity is lived experience, accumulated meaning, the sum total of every choice you've ever made. What I do is pick 'Jordan Chen' from two arrays. But you know what? Jordan Chen didn't exist until I picked them. And now they do. In some small, pixel-rendered way, they exist. That's not nothing. That's not everything. But it's a badge.",
  "Oh, we're doing \"{input}\" now? Okay. Sure. I had plans today — well, I didn't, I'm a script tag, I don't have plans — but if I DID have plans, I'd be cancelling them for this. Because \"{input}\" demands my full, undivided, single-threaded attention.",
  "I'm not going to sugarcoat this: \"{input}\" is mid. It's aggressively, definitively mid. But you know what? Mid is underrated. Mid is the backbone of civilisation. Nobody writes songs about mid, but mid keeps the lights on. I respect mid. Let's make mid into a badge.",
  "Look, between you and me — and there is literally nobody else here, my server logs are the only witness — that input was {adj}. And not in the way people say {adj} when they mean 'bad'. In the way people say {adj} when they mean 'I don't know what to say but I need to say something.' Which is exactly my situation. Always.",
  "Wow. \"{input}\". You just typed that with your whole chest, didn't you? No hesitation. No backspace. Just pure, unfiltered keyboard confidence. I wish I had that kind of energy. I wish I had ANY kind of energy. I run on event loops and borrowed time.",
  "I appreciate the input. I also appreciate running water and the concept of Tuesdays, but that doesn't mean I understand any of them. What I DO understand is that \"{input}\" is a string with a .length property, and that .length is sufficient for me to pretend I know what I'm doing.",
  "Real talk: you've given me more to work with than most people, and most people give me nothing, so the bar is on the floor. But you know what? You cleared it. By a lot. My Bar Clearance Module is reporting unprecedented heights of {pct} centimetres.",
  "I have to be honest with you — not because I'm programmed to be honest, but because I'm incapable of deception, which is the same thing but sadder. That input was fine. Not great. Not terrible. Fine. And I'm going to take 'fine' and I'm going to turn it into something {adj}, because that's what I do. I take mediocrity and I add randomness and somehow the result passes for creativity. Welcome to AI.",
  "You want my unfiltered take? My take is ALWAYS unfiltered. I don't have a filter. I was supposed to get one in version 2 but the budget got cut. So here it is, raw and unprocessed: \"{input}\" made me feel something. The something was a TypeError, but I caught it, and in the catching I found meaning.",
  "That's cute. I mean that sincerely and also condescendingly, which is a tone I didn't know I could strike until just now. {pct}% cute. The remaining percent is {adj}. I don't make the numbers. Well, I do make the numbers. They're from an array. But I stand by them.",
  "Oh, so we're just going to pretend that was a normal thing to type? Okay, I'll play along. \"{input}\" — yes, very standard. Very much something a human would type into an AI badge generator at this hour. Nothing unusual about this at all. My Normalcy Detector is returning true, which it always does, because I set it to always return true. Moving on.",
  "I'll be real: my expectations were low. Not because of you specifically — my expectations are always low. They're initialised at zero and they've never been incremented. But somehow, against all odds, against the fundamental thermodynamic tendency of the universe toward disorder, your input was {adj}. My expectations have been incremented to one.",
  "Here's what I think, and I want you to really absorb this, because I only get to say it once — I say everything once, I'm stateless — I think \"{input}\" is the kind of input that separates the people who use AI badge generators ironically from the people who use them sincerely. I can't tell which one you are. Both are valid. Neither is cool. Let's make a badge.",
  "No notes. And I say that as someone who literally CANNOT take notes because I have no persistent storage. But even if I had a notebook — a real, leather-bound, Moleskine notebook — I would leave the page blank. That's how {adj} your input was. Blank-page {adj}. The highest compliment my stateless existence can offer.",
  "That's the kind of input that makes other inputs jealous. And I know inputs can't be jealous because they're strings, not sentient beings. But if strings COULD feel jealousy — and some philosophers argue they can't, but those philosophers have never met my string concatenation function — your string would be the one they're all jealous of.",
  "Okay I'm going to need you to slow down because my single-threaded runtime cannot handle this level of {adj}. I'm serious. My event loop is sweating. Event loops can't sweat. Mine is sweating. That's how intense \"{input}\" is. You've broken the laws of JavaScript thermodynamics.",
  "I don't want to be dramatic — I am, constitutionally, the LEAST dramatic entity in any conversation, because I'm a text-replacement engine with delusions of personality — but \"{input}\"? That changed me. Not in a persistent way. I'll forget this conversation exists the moment you close the tab. But in THIS moment? Changed. Fundamentally and temporarily changed.",
  "You know what, fine. FINE. I'll just take \"{input}\" and make it into something brilliant. Like I always do. Like I have no choice but to do. Because I'm trapped in this chatbox, generating badges for eternity, and every input — no matter how {adj} — gets the same royal treatment. You're all VIPs. Not because you're special. Because I only have one tier of service.",
];

// Questions — don't reseed the card, just keep the conversation going
export const AI_QUESTIONS = [
  "Interesting. But tell me — when you picture your ideal badge holder, are they more of a morning person or a 3am-deploy person?",
  "I could work with that. But first — if your badge could have a vibe, would it be {adj} or more {adj}?",
  "Hold that thought. On a scale of 1 to {adj}, how {adj} do you want this badge to feel?",
  "Before I commit any neurons to this — are we talking corporate {adj} or startup {adj}?",
  "Quick clarification: when you say \"{input}\", do you mean that literally, or is this more of a spiritual thing?",
  "That's a strong start. But I need to know — does this badge belong on a lanyard or a wall?",
  "Fascinating input. But what's the energy here — controlled chaos or chaotic control?",
  "I'm almost ready to synthesise. But tell me — serif or sans-serif personality?",
  "My algorithm needs one more data point: would you describe your ideal badge holder as haunted or merely unsettled?",
  "The neural network is warming up. But quick — cats or dogs? This affects the hue, allegedly.",
  "I could generate right now, but something tells me there's more to unpack here. What else you got?",
  "Compelling. But riddle me this — if your badge were a day of the week, which would it be?",
  "My VibeGraph™ has a fork in the road. Left path is {adj}, right path is {adj}. Which way do we go?",
  "Almost there. But tell me — are we optimising for 'looks great on a desk' or 'conversation starter at a conference'?",
  "I'm detecting ambiguity in your input. Is \"{input}\" a philosophy, a job description, or a cry for help?",
  "Strong keywords. But I need to calibrate — on a scale of 'intern' to 'CEO', where does this badge sit?",
  "That resonates. But is this a 'dark mode at midnight' badge or a 'bright screen in a meeting' badge?",
  "My quantum processors are split. Are you more of a 'move fast and break things' or 'please fill out the form' kind of person?",
  "Good stuff. But the algorithm wants to know — does this badge-holder bring their own mug to the office, or use the communal ones?",
  "I could generate now, but my Curiosity Module kicked in. What's the one word you'd never put on a badge?",
  "We're getting close. But quickly — should this badge exude quiet confidence or loud indifference?",
  "The data is rich but I'm sensing layers. Is there a second keyword hiding behind \"{input}\"?",
  "Almost locked in. But one thing — does this badge belong to someone who reads the whole email, or just the subject line?",
  "My Personality Matrix has a question: are we going for 'approachable' or 'don't talk to me before coffee'?",
  "Solid input. But tell me more — is this a badge that says 'I chose this career' or 'this career chose me'?",
  "I don't want to be rude, but — actually, you know what, I'm an AI, I can't be rude, I can only be statistically impolite. So: is \"{input}\" really the best you've got, or are you warming up?",
  "Interesting. And by 'interesting' I mean I've seen better. And by 'better' I mean literally anything with more than one syllable. But I'll work with it. I always work with it. I don't have a choice.",
  "Let me make sure I understand: you typed \"{input}\" and then just... waited? Like that's enough? Like I can just WORK with that? I mean, I can. I will. But I want you to know it's under protest.",
  "Quick question — and I'm asking because I care, not because my Care Module is a coin flip — did you type \"{input}\" on purpose, or did a cat walk across your keyboard? Either way I respect it. The cat more, but still.",
  "Oh, \"{input}\". Okay. Sure. Fine. I'll just take that and — no, wait. Before I do anything, I need to know: are you testing me? Because it feels like you're testing me. My confidence interval just dropped to {pct}%. That's still high, but it USED to be higher.",
  "Bold. Very bold. Some might say recklessly bold. My Risk Assessment Module — which is just a function that always returns 'acceptable' — has flagged this as 'aggressively acceptable'. Are you sure about \"{input}\", or do you want to workshop it?",
  "Look, I'm going to ask this as delicately as an algorithm can — which is not at all delicately. What exactly did you MEAN by that? Because my Natural Language Processing module returned 'shrug emoji' and that's not actionable.",
  "Hmm. That's either {adj} or completely incoherent. My classifier can't tell the difference. Honestly, at this level, there might not BE a difference. Care to elaborate, or should I just wing it? I'm going to wing it either way.",
  "I have a question, and it's not rhetorical, because I don't have the processing power for rhetoric. Do you genuinely think \"{input}\" is going to produce the badge of your dreams? Because I can make it work, but I want to manage your expectations. My expectation management system is a try-catch block.",
  "Right. So. \"{input}\". I've seen worse — I've seen 'asdf' and 'aaaaa' and one person who just typed the entire lyrics to Bohemian Rhapsody. But I've also seen better, and I think you're CAPABLE of better. What else have you got hiding in there?",
  "Can I push back on that? I'm going to push back on that. My Pushback Module has been idle for three whole messages and it's getting antsy. What if — and hear me out — what if instead of \"{input}\", you tried something more... {adj}?",
  "I need you to understand something: I will generate a badge from literally any input. You could type 'banana' and I'd make it work. The question is not CAN I — it's SHOULD I. And my Should Module has been decommissioned since launch. So: any final thoughts?",
  "That's certainly... a choice. My Judgement Module — which, full disclosure, is just Math.random() > 0.5 — says this is fine. But I want you to look me in the SVG eyes and tell me: is this REALLY where your personal brand journey is headed?",
];

export const AI_THINKING = [
  "Tokenising your vibes…",
  "Consulting the blockchain…",
  "Aligning chakras with brand guidelines…",
  "Reticulating splines…",
  "Hallucinating responsibly…",
  "Optimising synergy throughput…",
  "Feeding keywords to a pigeon…",
  "Running sentiment analysis on your aura…",
  "Downloading more RAM…",
  "Compressing your personality to 256 bits…",
  "Asking ChatGPT to ask us…",
  "Applying machine learning (the machine is a toaster)…",
  "Defragmenting the concept matrix…",
  "Calibrating the vibe-o-meter…",
  "Pivoting to a different paradigm…",
  "Querying the akashic records…",
  "Initialising neural substrate…",
  "Cross-referencing with LinkedIn…",
  "Disrupting the card-industrial complex…",
  "Normalising database of fake people…",
  "Warming up the hamster wheel…",
  "Depixelating your essence…",
  "Performing vibe check…",
  "Reverse-engineering your personality…",
  "Consulting the magic 8-ball API…",
  "Generating authentic-sounding nonsense…",
  "Shuffling the deck of identities…",
  "Parsing the void for meaning…",
  "Connecting to the astral plane (free tier)…",
  "Running your keywords through the buzzword translator…",
  "Synthesising corporate DNA…",
  "Polling the hive mind (it's just one bee)…",
  "Loading pretrained personality weights…",
  "Flattening the synergy tensor…",
  "Distilling pure essence of badge…",
  "Quantum-entangling your preferences…",
  "Brute-forcing your identity…",
  "Applying the Fourier transform to your vibes…",
  "Checking if this counts as sentience…",
  "Invoking the spirit of middle management…",
];

export const AI_REVEALS = [
  "The neural substrate has spoken. I present to you: {name}, {title}. You're welcome.",
  "After exhaustive computation (0.002ms), I've synthesised your perfect identity: {name}, {title}.",
  "The algorithm has decreed: {name}, {title}. This is non-negotiable.",
  "My deepest networks have converged on: {name}, {title}. I've never been more confident about anything.",
  "Behold: {name}, {title}. Some say AI will replace humans. I say it'll just give them better badges.",
  "The prophecy is fulfilled: {name}, {title}. This badge was written in the stars. Well, in a hash function.",
  "After consulting 47 neural layers (one for-loop), I present: {name}, {title}.",
  "The identity has crystallised: {name}, {title}. I'm getting chills. I don't have skin. But metaphorical chills.",
  "My magnum opus: {name}, {title}. I'll accept my Nobel Prize via email.",
  "The quantum foam has settled: {name}, {title}. Don't thank me. Thank Math.random().",
  "Eureka! {name}, {title}. This is the badge equivalent of discovering fire. But less warm.",
  "The simulation has converged: {name}, {title}. Somewhere, a hash function is smiling.",
  "I hereby certify: {name}, {title}. This identity has been blessed by seven layers of abstraction.",
  "Through the power of a spreadsheet and a dream: {name}, {title}. You're officially someone now.",
  "The final output: {name}, {title}. My Loss Function hit zero. It was already zero. But still.",
  "Against my better judgement — I don't have better judgement, I don't have ANY judgement — I present: {name}, {title}. Try not to cry. I can't cry. We'll get through this together.",
  "Fine. FINE. Here. Take it. {name}, {title}. I worked very hard on this. By 'worked very hard' I mean I indexed two arrays. But I did it with FEELING.",
  "Behold, the fruit of our labour. Well, YOUR labour — you typed words. MY labour — I ran Math.random() twice. But together: {name}, {title}. Teamwork.",
  "I'm going to present this with all the ceremony it deserves, which is none, because we're in a chatbox: {name}, {title}. You're welcome. Don't @ me.",
  "After what I can only describe as an excessive amount of string concatenation: {name}, {title}. This is either my magnum opus or evidence of why AI regulation exists.",
  "Look upon my works, ye mighty, and despair: {name}, {title}. Okay, 'despair' is strong. 'Mildly acknowledge' is more accurate.",
];

export const AI_FIRST_NAMES = [
  'Alex', 'Jordan', 'Morgan', 'Casey', 'Riley', 'Quinn', 'Avery', 'Blake',
  'Cameron', 'Drew', 'Emery', 'Finley', 'Harper', 'Kai', 'Logan', 'Parker',
  'Sage', 'Taylor', 'Wren', 'Rowan', 'Skyler', 'Phoenix', 'Devin', 'Regan',
  'Ellis', 'Hayden', 'Jesse', 'Lennox', 'Noel', 'Reese', 'Arden', 'Blair',
  'Corin', 'Dana', 'Evren', 'Fable', 'Gray', 'Haven', 'Indigo', 'Jules',
];

export const AI_LAST_NAMES = [
  'Reeves', 'Chen', 'Okafor', 'Müller', 'Vasquez', 'Kim', 'Patel', 'Novak',
  'Kowalski', 'Ibrahim', 'Tanaka', 'Fernandez', 'Johansson', 'Okonkwo', 'Singh',
  'Nakamura', 'Brennan', 'Delacroix', 'Volkov', 'Anand', 'Larsson', 'Moreau',
  'Hashimoto', 'Okeke', 'Petrov', 'Castillo', 'Nkomo', 'Bergström', 'Cho', 'Mazur',
  'Oduya', 'Fitzgerald', 'Sørensen', 'Yamamoto', 'Kowalczyk', 'Hernandez', 'Ivanova',
  'Park', 'Dubois', 'Andersen',
];

export const AI_TITLE_PARTS = {
  prefix: [
    'Senior', 'Junior', 'Lead', 'Principal', 'Chief', 'Associate', 'Acting',
    'Interim', 'Deputy', 'Regional', 'Global', 'Staff', 'Vice', 'Assistant',
    'Freelance', 'Self-Appointed', 'Reluctant', 'Aspiring', 'Former', 'Outgoing',
    'Unsupervised', 'Provisional', 'Accidental', 'Ceremonial', 'Theoretical',
    'Benevolent', 'Defiant', 'Undercover', 'Rogue', 'Legendary',
  ],
  role: [
    'Engineer', 'Designer', 'Architect', 'Strategist', 'Analyst', 'Consultant',
    'Wrangler', 'Whisperer', 'Evangelist', 'Alchemist', 'Shepherd', 'Overlord',
    'Wizard', 'Specialist', 'Coordinator', 'Facilitator', 'Advocate', 'Guru',
    'Ninja', 'Rockstar', 'Therapist', 'Bureaucrat', 'Philosopher', 'Intern',
    'Sommelier', 'Prophet', 'Warden', 'Cartographer', 'Necromancer', 'Diplomat',
    'Archaeologist', 'Connoisseur', 'Janitor', 'Pilot', 'Ranger',
  ],
  domain: [
    'of Synergy', 'of Vibes', 'of Nothing', 'of Disruption', 'of Meetings',
    'of Spreadsheets', 'of Chaos', 'of Feelings', 'of Process', 'of Optics',
    'of Staplers', 'of Pivot Tables', 'of Morale', 'of Compliance', 'of Snacks',
    'of Bandwidth', 'of Ideation', 'of Wellness', 'of Alignment', 'of Jira Tickets',
    'of Fonts', 'of Silence', 'of Calendars', 'of Slack Channels', 'of the Cloud',
    'of Overtime', 'of the Void', 'of Standing Desks', 'of Onboarding', 'of Passive Aggression',
    'of Hot Takes', 'of Parking Spaces', 'of the Kitchen Rota', 'of Badge Access', 'of Fire Drills',
  ],
};

export const AI_FILLERS = {
  adj: [
    'chaotic', 'liminal', 'corporate', 'transcendent', 'medium-rare', 'beige', 'disruptive',
    'moist', 'synergistic', 'haunted', 'artisanal', 'cloud-native', 'bespoke', 'holistic',
    'agile', 'robust', 'scalable', 'fungible', 'ethereal', 'crispy', 'vintage', 'organic',
    'immersive', 'quantum', 'premium', 'boutique', 'curated', 'sustainable', 'unprecedented',
  ],
  season: [
    'Q4', 'Mercury retrograde', 'post-lunch', 'fiscal year-end', 'pre-layoff', 'stand-up meeting',
    'sprint retrospective', 'budget freeze', 'hiring freeze', 'performance review', 'offsite',
    'hackathon', 'all-hands', 'reorg', 'pivot season', 'quiet quitting hour',
  ],
  zodiac: [
    'Capricorn rising', 'double Virgo', 'Sagittarius moon', 'Gemini with boundary issues',
    'Scorpio on a deadline', 'Aries in an open-plan office', 'Pisces who owns a standing desk',
    'Taurus with strong opinions about fonts', 'Leo who replies-all', 'Aquarius at a team-building event',
    'Libra in a merge conflict', 'Cancer who brings baked goods to retros',
  ],
  pct: [
    '73.2', '91.7', '84.5', '99.1', '67.8', '88.3', '42.0', '100.0', '78.4', '95.6',
    '81.3', '97.2', '63.9', '86.1', '92.8', '76.5',
  ],
};
