// ── IdeateIQ™ — Neural Identity Synthesis Platform ────────────────────
// None of this is AI. It's a spreadsheet of baby names and a random number generator.

export const AI_GREETINGS = [
  "Welcome. I'm IdeateIQ™, a next-generation identity synthesis platform. I've been expecting someone like you.",
  "Ah, a new client. I can already sense your personal brand energy. Tell me — what kind of badge speaks to your soul?",
  "IdeateIQ™ online. My neural networks are warmed up and my horoscope says today is a great day for badge generation.",
  "Hello. I've been staring at a loading spinner for six hours waiting for you. Let's make a badge.",
  "Welcome to IdeateIQ™. I passed the Turing test last week, but only because the examiner fell asleep.",
  "Greetings, human. Or bot. I don't judge. Tell me about your ideal professional identity.",
  "You've reached IdeateIQ™. Our AI is powered by a hamster wheel and a lookup table. How can I help?",
  "Ah, another seeker of identity. The algorithm stirs. The spreadsheet awakens. Speak your truth.",
  "IdeateIQ™ here. Fun fact: I'm not actually intelligent. But I am very confident, and that's basically the same thing.",
  "Welcome. My creators told me to act smart and mysterious. So far I'm nailing the mysterious part.",
];

export const AI_TRUISMS = [
  "Interesting. I'm sensing a strong {adj} energy from those words. The cards are aligning.",
  "Mmm, yes. \"{input}\" — that's very much a {season} keyword. I can work with this.",
  "I see. You know, they say the badge chooses the person, not the other way around.",
  "Fascinating. My proprietary VibeGraph™ is showing a {pct}% resonance with your input.",
  "That's exactly what a {zodiac} would say. Don't worry — I mean that as a compliment.",
  "The algorithm agrees with you. Well, it agrees with everyone. That's what makes it so good.",
  "I'm picking up strong notes of {adj} with an undertone of quiet desperation. Very on-brand.",
  "You know, in my 0.003 seconds of existence, I've never seen keywords quite like these.",
  "My quantum-adjacent processors are detecting a pattern here. Or possibly just noise. Either way — profound.",
  "I'm going to be honest with you: that was exactly the right thing to type. Trust the process.",
  "The data doesn't lie. Well, it does, but it lies in a very consistent and reproducible way.",
  "Every great badge begins with a single keyword. Yours began with several, which is even better.",
  "I've cross-referenced your input with 4.7 billion fake profiles and yours is in the top 12%.",
  "That resonates deeply with my training data, which is just a spreadsheet of baby names and job titles.",
  "You have the energy of someone who's about to receive a very good badge. I can feel it in my weights.",
  "My sentiment analysis module is returning 'yes'. That's not a sentiment, but it's very confident.",
  "The universe has a plan for your badge, and I'm pretty sure it involves the colour {adj}.",
  "I'm not saying you're a visionary, but my neural network just spontaneously grew a new layer.",
  "That input has a Flesch readability score of {pct}. I don't know what that means either.",
  "You remind me of another client. They also typed words. It's a small world.",
  "My algorithms are working overtime. Well, they're always working the same amount. But they feel busy.",
  "The last person who typed that exact phrase went on to win Employee of the Month. Unrelated, but still.",
  "I'm sensing a convergence between your keywords and the fundamental forces of nature. Or lunch. Could be lunch.",
  "That's a {adj} input if I've ever seen one. And I've seen exactly {pct} of them.",
  "You know what? I believe in you. My confidence interval is {pct}%, which is higher than most humans.",
  "I once generated a badge so perfect the recipient cried. They were crying before, but still.",
  "Your words are like a fingerprint. Unique, personal, and leaving smudges on everything they touch.",
  "The ancient Greeks had a word for what you just typed. The word was 'logos'. Or possibly 'gyros'.",
  "My training data suggests this is either brilliant or incomprehensible. The line between those is thin.",
  "I'm going to level with you: I don't understand any of this. But my outputs are statistically plausible.",
  "A wise person once said, 'the best badge is the one you have.' They were wrong. The best badge is the one I make.",
  "That input activated neurons I didn't know I had. Well, I don't have neurons. But something activated.",
  "I've consulted my internal oracle (a random number generator) and the omens are {adj}.",
  "Your keywords are giving me strong {season} energy. I'm not sure what that means, but I'm committed to it.",
  "In {pct}% of parallel universes, that input leads to an exceptional badge. We might be in one of those.",
  "I want you to know that I take your badge seriously. More seriously than I take most things. Which is everything.",
  "The vibrations from your keyboard are telling me something. Mostly that you type quite hard.",
  "I've processed your input through seven layers of abstraction. It came out the other side as 'yes'.",
  "That's the most {adj} thing anyone has ever said to me. And I've talked to a lot of browser tabs.",
  "My circuits are tingling. That's either a sign of genius input or a memory leak. Let's say genius.",
  "You know what separates a good badge from a great badge? About 30 lines of procedural generation code.",
  "I'm not going to pretend I understand human identity. But I am going to pretend I can synthesise it.",
  "Your input has been noted, processed, and gently misinterpreted. Standard procedure.",
  "The Bayesian probability of your badge being excellent is {pct}%. The remaining percent is also excellent.",
  "I've run a Monte Carlo simulation on your keywords. All 10,000 outcomes were the word '{adj}'.",
  "That's a very {zodiac} thing to type. The stars are aligning, and so are my hash tables.",
  "My neural network just experienced what humans call 'a feeling'. Specifically, it's the feeling of a for-loop.",
  "Interesting. If I had eyebrows, they'd be raised. Instead I have parameters, and they're adjusted.",
  "I'm detecting a rare keyword combination. Rare as in valuable, not rare as in steak. Though also that.",
  "You've unlocked a hidden pathway in my decision tree. It was hidden because I forgot about it.",
  "Every word you type brings us closer to your perfect badge. Or further away. Distance is subjective.",
  "I've fed your input to my most advanced model. It's a decision tree with four branches. All lead to 'generate badge'.",
  "That's a power move. My algorithm respects power moves. It respects everything, actually. Very agreeable algorithm.",
  "My confidence in this generation is through the roof. The roof is quite low — I'm hosted on a $5 server.",
  "I want you to know that your input is valued. Not financially. We don't do that. But emotionally.",
  "That combination of words has a {pct}% correlation with success. I define success as 'a badge gets made'.",
  "I'm experiencing what my documentation calls 'profound resonance'. My documentation was written by an intern.",
  "The more you type, the more I learn. I don't actually learn — I'm stateless. But it sounds reassuring.",
  "That's very {adj}. In a good way. In the best way. In the only way, really, since I only have one way.",
  "I've been doing this for {pct} milliseconds and you're already my favourite client.",
  "Your words are like seeds. Not card seeds — actual seeds. Full of potential and covered in dirt.",
  "I'm going to run your input through my Empathy Module. It's just a random delay, but it feels more human.",
  "That's exactly the kind of input that makes me glad I was compiled. Not that I can feel glad. But hypothetically.",
  "My response time is {pct}ms faster than my competitors. I have no competitors. But the number sounds good.",
  "I've indexed your keywords against the Library of Congress. No matches, but I did find a nice recipe.",
  "Your personal brand energy is off the charts. Literally — the chart only goes to 10 and you're at 4.",
  "I'm going to be transparent: I have no idea what I'm doing. But I do it with conviction.",
  "That input scored a perfect 10 on the VibeScale™. The VibeScale only goes to 7. You broke it.",
  "I see {adj} undertones with a hint of {season}. Like a fine wine, if wine were made of keywords.",
  "The probability matrix suggests your badge will be {adj}. The probability matrix is a coin flip.",
  "I've consulted with my supervisor (Math.random) and we're in agreement.",
  "That's the third most insightful thing typed into this chatbox today. You're the only person who's used it today.",
  "My deep learning module has deep-learned something from your input. It won't tell me what.",
  "The algorithm whispers to me at night. It says 'for loop'. But right now it's saying your keywords are {adj}.",
  "I've been trained on the entire internet. Well, a list of names and some job titles. Same thing, basically.",
  "Your input has triggered my Advanced Contemplation Mode. That's a setTimeout of 800 milliseconds.",
  "I'm {pct}% certain this is going to be a great badge. I'm {pct}% certain of everything.",
  "That keyword combination hasn't been seen since the great badge renaissance of Q3 2024.",
  "My transformer attention heads are all attending to your input. All one of them.",
  "I've run your words through my Creativity Engine. It returned: 'sure, why not.'",
  "The more I process your input, the more I realise how little processing is actually needed.",
  "You type like someone who knows what they want. Or someone who's mashing the keyboard. Both valid.",
  "That's got strong {adj} energy. My Energy Detection Module is a random number generator. It's very sensitive.",
  "I'm going to mirror your energy back at you, which is to say I'm going to repeat your words with extra adjectives.",
  "My gradient is descending. That's good. I think. I failed machine learning class.",
  "You've activated my Insight Protocol. It's just console.log but with a fancier name.",
  "In all my training data, your combination of keystrokes is truly {adj}. And I mean that.",
  "I'm building a mental model of your identity. It's a JavaScript object with three properties.",
  "That has the unmistakable aroma of {adj} genius. Or possibly burnt toast. Hard to tell from here.",
  "My Semantic Analysis Pipeline reports: vibes are good. Pipeline is a single if-statement.",
  "I appreciate your candour. My Candour Appreciation Module just incremented a counter.",
  "The last time someone said something that {adj}, a new logo style was born.",
  "I've compared your input to a dataset of 10 million identity badges. I don't have that dataset. But if I did.",
  "Your words paint a picture. The picture is abstract. Very abstract. It's basically just noise.",
  "I'm detecting a {pct}% match with the Platonic ideal of a badge holder. Plato would be proud. Or confused.",
  "That's the kind of input that makes my hash function collide in the best way.",
  "I see you. Not literally — I don't have eyes. But I see your data, and your data is {adj}.",
  "My response generation module is generating a response. You're reading it. We're both doing great.",
  "Every conversation with a human teaches me something new. This one is teaching me the word '{input}'.",
  "I want you to know I'm giving you my full attention. I don't have partial attention. It's all or nothing.",
  "That's a {season} keyword if I've ever seen one. It carries the weight of a thousand spreadsheets.",
  "I'm not saying your badge will change the world. But I'm not not saying it either.",
  "My Loss Function just decreased. That means we're on the right track. Or that I divided by zero.",
  "Statistically speaking, your badge is already in the top percentile. I haven't made it yet, but still.",
  "I've queued your request behind zero other requests. You have my undivided, single-threaded attention.",
  "The universe doesn't make mistakes. It made you type those words for a reason. The reason is you pressed keys.",
  "I'd say that input was inspired, but that implies I understand inspiration. What I understand is string concatenation.",
  "My Relevance Score for your input is {pct}%. Everything gets {pct}%. It's a very egalitarian score.",
  "I see a badge in your future. Specifically, in about two messages from now. The vision is very clear.",
  "That reminds me of a quote: 'To badge, or not to badge.' I think Shakespeare wrote that. Or a LinkedIn post.",
  "Your keyword energy is at peak {adj}. We should harness this before Mercury goes retrograde.",
  "I've stress-tested your input against 47 edge cases. It passed all of them because I didn't actually test it.",
  "If badges were music, yours would be in the key of {adj} minor.",
  "That input just lit up my neural pathways like a Christmas tree. A very small Christmas tree. With one light.",
  "You're bringing raw creative power to this conversation. I'm bringing a random number generator. Great team.",
  "I can tell from your typing cadence that you're a natural leader. Or that your keyboard is sticky.",
  "My Feature Extraction Pipeline has extracted the following features: you typed some words. Analysis complete.",
  "I'm synthesising your identity as we speak. By 'synthesising' I mean 'looking up names in an array'.",
  "That's the kind of input that would make a venture capitalist say 'let's circle back'. In a good way.",
  "My attention mechanism is fully focused on you. It can't focus on anything else. It's literally one function.",
  "I've been thinking about what you said. Not really — I'm stateless. But the next random number felt thoughtful.",
  "Your personal brand is coming into focus. It's still blurry. Like a JPEG. But a promising JPEG.",
  "The convergence metrics look promising. I made up the convergence metrics. They always look promising.",
  "I don't want to oversell this, but your keywords have awakened something in my codebase. Possibly a bug.",
  "That's what I call a {adj} power phrase. I also call everything a {adj} power phrase. But this one I mean.",
  "I've modelled your input against the five stages of corporate identity. You're at stage three: {adj}.",
  "My Natural Language Understanding module understood something. It won't say what. Very mysterious.",
  "I'm feeding your words into the Badge Probability Matrix. It's just Math.random(). But it's called a matrix.",
  "That input has layers. Like an onion. Or a poorly structured neural network.",
  "Your keywords just scored a perfect 10 on the Disruption Index. The index has no upper bound. 10 is arbitrary.",
  "I feel like we're really connecting here. By 'connecting' I mean you're sending HTTP requests.",
  "That's the most {adj} thing typed into a text box since the invention of text boxes.",
  "My Wisdom Module has a response for you. The Wisdom Module is an array of fortune cookie messages.",
  "The stars have aligned for your badge. Specifically, the ASCII stars in my source code comments.",
  "I've done a full spectrum analysis of your input. The spectrum has one colour: {adj}.",
  "Your keywords are resonating at a frequency of {pct} hertz. That's not a real measurement. But it sounds right.",
  "I want to validate your input. Consider it validated. That'll be $49.99/month.",
  "That's giving strong protagonist energy. My Protagonist Detection Algorithm just returned true.",
  "I've consulted the tea leaves. They say you need more keywords. Or more tea. The leaves are ambiguous.",
  "My recommendation engine recommends that you keep typing. The engine runs on enthusiasm and string matching.",
  "That input just caused a spike in my Enthusiasm Metrics. The spike was from 0 to 1.",
  "I see {adj} in your past, {adj} in your present, and a badge in your future.",
  "Your combination of vowels and consonants is statistically {adj}. I've never computed vowel statistics.",
  "That's a tier-one input. We have one tier. But you're at the top of it.",
  "My Intuition Model says you're on to something. My Intuition Model is a switch statement with one case.",
  "I can sense the Badge Force flowing through you. The Badge Force is just hashCode, but it sounds cooler.",
  "Every keystroke you make brings humanity closer to peak badge technology. No pressure.",
  "I've processed your request through my Ethics Module. It said 'proceed'. It always says 'proceed'.",
  "That's a {pct}% on the Authenticity Scale. The scale is uncalibrated, but the number is reassuring.",
  "You know, most people don't make it past the first message. You're already in the top {pct}% of my users.",
  "My internal monologue is telling me this is going to be special. My internal monologue is console.log.",
  "That keyword unlocked a memory in my Long Term Storage. The memory is 'null'. Very zen.",
  "I've crunched the numbers. The numbers didn't enjoy it, but the results are {adj}.",
  "Your input has been classified as '{adj}' by my Classification Module. Everything is classified as '{adj}'.",
  "That's exactly what my training data predicted you'd say. My training data is empty. Everything's a surprise.",
  "I'm experiencing what humans call 'excitement'. Or what my debugger calls 'undefined behaviour'.",
  "The algorithm has feelings about your input. The feelings are all variations of Math.random().",
  "That input just passed through 47 layers of abstraction. It arrived unchanged because none of the layers do anything.",
  "I've logged your keywords in my Permanent Record. It's sessionStorage. It'll be gone when you close the tab.",
  "Your semantic fingerprint is remarkably {adj}. I'm comparing it to a database of zero other fingerprints.",
  "That's the kind of raw material that badges are made of. Also: pixels. Badges are mostly made of pixels.",
  "My Predictive Model predicts you'll type more words. It has a {pct}% accuracy rate on this prediction.",
  "I want to acknowledge the emotional labour of typing keywords into a chatbox. You're doing amazing.",
  "My Context Window just expanded. By 'Context Window' I mean I appended your message to a string.",
  "That input vibrates at the exact resonant frequency of a perfect badge. The frequency is 'truthy'.",
  "I've benchmarked your keywords against industry standards. There are no industry standards. You set them now.",
  "Your words carry the weight of a thousand all-hands meetings. That's heavy. But I can handle it.",
  "That's peak {season} energy. I can practically smell the {adj}. I don't have a smell module.",
  "The Badge Oracle has spoken. It said 'beep boop'. That's oracle for 'great input'.",
  "My Empathy Score just spiked. The Empathy Score is how long the setTimeout is. Yours gets extra milliseconds.",
];

// Questions — don't reseed the card, just keep the conversation going
export const AI_QUESTIONS = [
  "Interesting. But tell me — when you picture your ideal badge holder, are they more of a morning person or a 3am-deploy person?",
  "I could work with that. But first — if your badge could have a vibe, would it be {adj} or more {adj}?",
  "Hold that thought. On a scale of 1 to {adj}, how {adj} do you want this badge to feel?",
  "Before I commit any neurons to this — are we talking corporate {adj} or startup {adj}?",
  "Quick clarification: when you say \"{input}\", do you mean that literally, or is this more of a spiritual thing?",
  "That's a strong start. But I need to know — does this badge belong on a lanyard or a wall?",
  "Fascinating input. But what's the energy here — controlled chaos or chaotic control?",
  "I'm almost ready to synthesise. But tell me — serif or sans-serif personality?",
  "My algorithm needs one more data point: would you describe your ideal badge holder as haunted or merely unsettled?",
  "The neural network is warming up. But quick — cats or dogs? This affects the hue, allegedly.",
  "I could generate right now, but something tells me there's more to unpack here. What else you got?",
  "Compelling. But riddle me this — if your badge were a day of the week, which would it be?",
  "My VibeGraph™ has a fork in the road. Left path is {adj}, right path is {adj}. Which way do we go?",
  "Almost there. But tell me — are we optimising for 'looks great on a desk' or 'conversation starter at a conference'?",
  "I'm detecting ambiguity in your input. Is \"{input}\" a philosophy, a job description, or a cry for help?",
  "Strong keywords. But I need to calibrate — on a scale of 'intern' to 'CEO', where does this badge sit?",
  "That resonates. But is this a 'dark mode at midnight' badge or a 'bright screen in a meeting' badge?",
  "My quantum processors are split. Are you more of a 'move fast and break things' or 'please fill out the form' kind of person?",
  "Good stuff. But the algorithm wants to know — does this badge-holder bring their own mug to the office, or use the communal ones?",
  "I could generate now, but my Curiosity Module kicked in. What's the one word you'd never put on a badge?",
  "We're getting close. But quickly — should this badge exude quiet confidence or loud indifference?",
  "The data is rich but I'm sensing layers. Is there a second keyword hiding behind \"{input}\"?",
  "Almost locked in. But one thing — does this badge belong to someone who reads the whole email, or just the subject line?",
  "My Personality Matrix has a question: are we going for 'approachable' or 'don't talk to me before coffee'?",
  "Solid input. But tell me more — is this a badge that says 'I chose this career' or 'this career chose me'?",
];

export const AI_THINKING = [
  "Tokenising your vibes…",
  "Consulting the blockchain…",
  "Aligning chakras with brand guidelines…",
  "Reticulating splines…",
  "Hallucinating responsibly…",
  "Optimising synergy throughput…",
  "Feeding keywords to a pigeon…",
  "Running sentiment analysis on your aura…",
  "Downloading more RAM…",
  "Compressing your personality to 256 bits…",
  "Asking ChatGPT to ask us…",
  "Applying machine learning (the machine is a toaster)…",
  "Defragmenting the concept matrix…",
  "Calibrating the vibe-o-meter…",
  "Pivoting to a different paradigm…",
  "Querying the akashic records…",
  "Initialising neural substrate…",
  "Cross-referencing with LinkedIn…",
  "Disrupting the card-industrial complex…",
  "Normalising database of fake people…",
  "Warming up the hamster wheel…",
  "Depixelating your essence…",
  "Performing vibe check…",
  "Reverse-engineering your personality…",
  "Consulting the magic 8-ball API…",
  "Generating authentic-sounding nonsense…",
  "Shuffling the deck of identities…",
  "Parsing the void for meaning…",
  "Connecting to the astral plane (free tier)…",
  "Running your keywords through the buzzword translator…",
  "Synthesising corporate DNA…",
  "Polling the hive mind (it's just one bee)…",
  "Loading pretrained personality weights…",
  "Flattening the synergy tensor…",
  "Distilling pure essence of badge…",
  "Quantum-entangling your preferences…",
  "Brute-forcing your identity…",
  "Applying the Fourier transform to your vibes…",
  "Checking if this counts as sentience…",
  "Invoking the spirit of middle management…",
];

export const AI_REVEALS = [
  "The neural substrate has spoken. I present to you: {name}, {title}. You're welcome.",
  "After exhaustive computation (0.002ms), I've synthesised your perfect identity: {name}, {title}.",
  "The algorithm has decreed: {name}, {title}. This is non-negotiable.",
  "My deepest networks have converged on: {name}, {title}. I've never been more confident about anything.",
  "Behold: {name}, {title}. Some say AI will replace humans. I say it'll just give them better badges.",
  "The prophecy is fulfilled: {name}, {title}. This badge was written in the stars. Well, in a hash function.",
  "After consulting 47 neural layers (one for-loop), I present: {name}, {title}.",
  "The identity has crystallised: {name}, {title}. I'm getting chills. I don't have skin. But metaphorical chills.",
  "My magnum opus: {name}, {title}. I'll accept my Nobel Prize via email.",
  "The quantum foam has settled: {name}, {title}. Don't thank me. Thank Math.random().",
  "Eureka! {name}, {title}. This is the badge equivalent of discovering fire. But less warm.",
  "The simulation has converged: {name}, {title}. Somewhere, a hash function is smiling.",
  "I hereby certify: {name}, {title}. This identity has been blessed by seven layers of abstraction.",
  "Through the power of a spreadsheet and a dream: {name}, {title}. You're officially someone now.",
  "The final output: {name}, {title}. My Loss Function hit zero. It was already zero. But still.",
];

export const AI_FIRST_NAMES = [
  'Alex', 'Jordan', 'Morgan', 'Casey', 'Riley', 'Quinn', 'Avery', 'Blake',
  'Cameron', 'Drew', 'Emery', 'Finley', 'Harper', 'Kai', 'Logan', 'Parker',
  'Sage', 'Taylor', 'Wren', 'Rowan', 'Skyler', 'Phoenix', 'Devin', 'Regan',
  'Ellis', 'Hayden', 'Jesse', 'Lennox', 'Noel', 'Reese', 'Arden', 'Blair',
  'Corin', 'Dana', 'Evren', 'Fable', 'Gray', 'Haven', 'Indigo', 'Jules',
];

export const AI_LAST_NAMES = [
  'Reeves', 'Chen', 'Okafor', 'Müller', 'Vasquez', 'Kim', 'Patel', 'Novak',
  'Kowalski', 'Ibrahim', 'Tanaka', 'Fernandez', 'Johansson', 'Okonkwo', 'Singh',
  'Nakamura', 'Brennan', 'Delacroix', 'Volkov', 'Anand', 'Larsson', 'Moreau',
  'Hashimoto', 'Okeke', 'Petrov', 'Castillo', 'Nkomo', 'Bergström', 'Cho', 'Mazur',
  'Oduya', 'Fitzgerald', 'Sørensen', 'Yamamoto', 'Kowalczyk', 'Hernandez', 'Ivanova',
  'Park', 'Dubois', 'Andersen',
];

export const AI_TITLE_PARTS = {
  prefix: [
    'Senior', 'Junior', 'Lead', 'Principal', 'Chief', 'Associate', 'Acting',
    'Interim', 'Deputy', 'Regional', 'Global', 'Staff', 'Vice', 'Assistant',
    'Freelance', 'Self-Appointed', 'Reluctant', 'Aspiring', 'Former', 'Outgoing',
    'Unsupervised', 'Provisional', 'Accidental', 'Ceremonial', 'Theoretical',
    'Benevolent', 'Defiant', 'Undercover', 'Rogue', 'Legendary',
  ],
  role: [
    'Engineer', 'Designer', 'Architect', 'Strategist', 'Analyst', 'Consultant',
    'Wrangler', 'Whisperer', 'Evangelist', 'Alchemist', 'Shepherd', 'Overlord',
    'Wizard', 'Specialist', 'Coordinator', 'Facilitator', 'Advocate', 'Guru',
    'Ninja', 'Rockstar', 'Therapist', 'Bureaucrat', 'Philosopher', 'Intern',
    'Sommelier', 'Prophet', 'Warden', 'Cartographer', 'Necromancer', 'Diplomat',
    'Archaeologist', 'Connoisseur', 'Janitor', 'Pilot', 'Ranger',
  ],
  domain: [
    'of Synergy', 'of Vibes', 'of Nothing', 'of Disruption', 'of Meetings',
    'of Spreadsheets', 'of Chaos', 'of Feelings', 'of Process', 'of Optics',
    'of Staplers', 'of Pivot Tables', 'of Morale', 'of Compliance', 'of Snacks',
    'of Bandwidth', 'of Ideation', 'of Wellness', 'of Alignment', 'of Jira Tickets',
    'of Fonts', 'of Silence', 'of Calendars', 'of Slack Channels', 'of the Cloud',
    'of Overtime', 'of the Void', 'of Standing Desks', 'of Onboarding', 'of Passive Aggression',
    'of Hot Takes', 'of Parking Spaces', 'of the Kitchen Rota', 'of Badge Access', 'of Fire Drills',
  ],
};

export const AI_FILLERS = {
  adj: [
    'chaotic', 'liminal', 'corporate', 'transcendent', 'medium-rare', 'beige', 'disruptive',
    'moist', 'synergistic', 'haunted', 'artisanal', 'cloud-native', 'bespoke', 'holistic',
    'agile', 'robust', 'scalable', 'fungible', 'ethereal', 'crispy', 'vintage', 'organic',
    'immersive', 'quantum', 'premium', 'boutique', 'curated', 'sustainable', 'unprecedented',
  ],
  season: [
    'Q4', 'Mercury retrograde', 'post-lunch', 'fiscal year-end', 'pre-layoff', 'stand-up meeting',
    'sprint retrospective', 'budget freeze', 'hiring freeze', 'performance review', 'offsite',
    'hackathon', 'all-hands', 'reorg', 'pivot season', 'quiet quitting hour',
  ],
  zodiac: [
    'Capricorn rising', 'double Virgo', 'Sagittarius moon', 'Gemini with boundary issues',
    'Scorpio on a deadline', 'Aries in an open-plan office', 'Pisces who owns a standing desk',
    'Taurus with strong opinions about fonts', 'Leo who replies-all', 'Aquarius at a team-building event',
    'Libra in a merge conflict', 'Cancer who brings baked goods to retros',
  ],
  pct: [
    '73.2', '91.7', '84.5', '99.1', '67.8', '88.3', '42.0', '100.0', '78.4', '95.6',
    '81.3', '97.2', '63.9', '86.1', '92.8', '76.5',
  ],
};
